sudo: required
services:
  - docker

before_install:
  - docker build -t charlienlouie/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true charlienlouie/react-test npm test

after_success:
  - docker build -t charlienlouie/multi-client ./client
  - docker build -t charlienlouie/multi-nginx ./nginx
  - docker build -t charlienlouie/multi-server ./server
  - docker build -t charlienlouie/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push charlienlouie/multi-client
  - docker push charlienlouie/multi-nginx
  - docker push charlienlouie/multi-server
  - docker push charlienlouie/multi-worker

deploy:
  edue: true
  provider: elasticbeanstalk
  region: us-west-1
  app: "Multi-container Docker2"
  env: MultiContainerDocker2-env
  bucket_name: elasticbeanstalk-us-west-1-106687455341
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
